config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#index'

  root to: 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user


  validates :body, length: {minimum: 5}, presence: true
  validates :user_id, presence: true

  after_create :send_favorite_emails

  default_scope { order('updated_at DESC') }

  private

   def send_favorite_emails
    post.favorites.each do |favorite|
       if should_receive_update_for?(favorite)
        FavoriteMailer.new_comment(favorite.user, post, self).deliver
      end
    end
  end
 
   def should_receive_update_for?(favorite)
     user_id != favorite.user_id && favorite.user.email_favorites?
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :html, :js

  def create 
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    @comment = current_user.comments.build(comment_params)
    @comment.post = @post
    @new_comment = Comment.new

    authorize @comment
  
    if @comment.save
      flash[:notice] = "Comment was saved."
    else
      flash[:error] = "There was an error saving the comment. Please try again"
    end

    respond_with(@comment) do |format|
      format.html { redirect_to [@post.topic, @post]}
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @topic = @post.topic

    authorize @comment
    if @comment.destroy
      flash[:notice] = "Comment was removed"
    else
      flash[:error] = "Comment could not be deleted"
    end

    respond_with(@comment) do |format|
      format.html {redirect_to [@post.topic, @post]}
    end
  end


  private 

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="media">
  <%= content_tag :div, class: 'media', id: "comment-#{comment.id}" do %> 
    <%= link_to '#', class: 'pull-left' do %>
      <%= image_tag(comment.user.avatar.small.url) if comment.user.avatar? %>
    <% end %>
    <div class="media-body">
      <small>
        <%= comment.user.name %> commented <%= time_ago_in_words(comment.created_at) %> ago
        <% if policy(comment).destroy? %>
          <%= link_to "Delete", [comment.post, comment], method: :delete, remote: true %>
        <% end %>
      </small>
      <p><%= comment.body %></p>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @comment], url: post_comments_path(@post, @comment), remote: true do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger">
      <h4> There are <%= pluralize(@comment.errors.count, "error") %>.</h4>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :body, as: :text, input_html: { columns: 4, rows: 4, class: 'form-control'}, error: false %>
  <%= f.hidden_field :post_id, value: @post[:id] %>
  <%= f.button :submit, class: 'btn-success' %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $('.js-comments').prepend("<%= escape_javascript(render(@comment)) %>");
  $('.new-comment').html("<%= escape_javascript(render partial: 'comments/form', locals: { post: @post, comment: @new_comment }) %>");
<% else %>
  $('.new-comment').html("<%= escape_javascript(render partial: 'comments/form', locals: { post: @post, comment: @comment }) %>");
<% end %>

app/views/comments/destroy.js.erb
<% if @comment.destroyed? %>
  $('#comment-' +<%= @comment.id %>).hide();
  $('.js-comments-count').html("<%= @comment.user.comments.count %> comments");
<% else %>
  $('#comment-' +<%= @comment.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>  